name: Node.js CI

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
      - name: Pre-Deployment
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install && npm install typescript -g && npm install ts-node -g
      - run: npm run db:generate
      - run: npm run db:migrate
      - run: curl https://api.render.com/deploy/srv-cqdls61u0jms738rsffg?key=foEtJr7_Y-U
